# Main FMC configuration file
# ---
enable-colorme: true
enable-oneplayersleep: true
enable-dynfmc: true
enable-afk: true
enable-stats: true
enable-chatter: true
enable-loot: true
enable-fun: true